# Generated by Django 3.2.16 on 2023-01-18 00:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geoscience", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="earthmaterial",
            options={"verbose_name": "BGS Earth Material", "verbose_name_plural": "BGS Earth Materials"},
        ),
    ]
