# Generated by Django 5.0.7 on 2024-08-12 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("measurements", "0002_initial"),
        ("samples", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomParentSample",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="samples.sample",
                    ),
                ),
                (
                    "char_field",
                    models.CharField(
                        help_text="Enter a string of up to 200 characters.",
                        max_length=200,
                        verbose_name="Character Field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Sample",
                "verbose_name_plural": "Custom Samples",
            },
            bases=("samples.sample",),
        ),
        migrations.CreateModel(
            name="CustomSample",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="samples.sample",
                    ),
                ),
                (
                    "char_field",
                    models.CharField(
                        help_text="Enter a string of up to 200 characters.",
                        max_length=200,
                        verbose_name="Character Field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Sample",
                "verbose_name_plural": "Custom Samples",
            },
            bases=("samples.sample",),
        ),
        migrations.CreateModel(
            name="ExampleMeasurement",
            fields=[
                (
                    "measurement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="measurements.measurement",
                    ),
                ),
                (
                    "float_field",
                    models.FloatField(
                        help_text="Enter a floating point number.",
                        verbose_name="Float Field",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("measurements.measurement",),
        ),
    ]
