# Generated by Django 5.0.7 on 2024-08-12 10:41

import django.db.models.deletion
import earth_science.vocabularies.odm2
import research_vocabs.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("samples", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrillCore",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="samples.sample",
                    ),
                ),
                (
                    "feature_type",
                    research_vocabs.fields.ConceptField(
                        default="specimen",
                        editable=False,
                        verbose_name="",
                        vocabulary=earth_science.vocabularies.odm2.SamplingFeatureType,
                    ),
                ),
                (
                    "medium",
                    research_vocabs.fields.ConceptField(
                        default="rock",
                        editable=False,
                        verbose_name="medium",
                        vocabulary=earth_science.vocabularies.odm2.Medium,
                    ),
                ),
                (
                    "specimen_type",
                    research_vocabs.fields.ConceptField(
                        default="core",
                        verbose_name="specimen",
                        vocabulary=earth_science.vocabularies.odm2.SpecimenType,
                    ),
                ),
            ],
            options={
                "verbose_name": "drill core",
                "verbose_name_plural": "drill cores",
                "abstract": False,
            },
            bases=("samples.sample",),
        ),
        migrations.CreateModel(
            name="RockSample",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="samples.sample",
                    ),
                ),
                (
                    "feature_type",
                    research_vocabs.fields.ConceptField(
                        default="specimen",
                        editable=False,
                        verbose_name="",
                        vocabulary=earth_science.vocabularies.odm2.SamplingFeatureType,
                    ),
                ),
                (
                    "medium",
                    research_vocabs.fields.ConceptField(
                        default="rock",
                        editable=False,
                        verbose_name="medium",
                        vocabulary=earth_science.vocabularies.odm2.Medium,
                    ),
                ),
                (
                    "specimen_type",
                    research_vocabs.fields.ConceptField(
                        default="individualSample",
                        editable=False,
                        verbose_name="specimen",
                        vocabulary=earth_science.vocabularies.odm2.SpecimenType,
                    ),
                ),
            ],
            options={
                "verbose_name": "rock sample",
                "verbose_name_plural": "rock samples",
                "abstract": False,
            },
            bases=("samples.sample",),
        ),
        migrations.CreateModel(
            name="ThinSection",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="samples.sample",
                    ),
                ),
                (
                    "feature_type",
                    research_vocabs.fields.ConceptField(
                        default="specimen",
                        editable=False,
                        verbose_name="",
                        vocabulary=earth_science.vocabularies.odm2.SamplingFeatureType,
                    ),
                ),
                (
                    "medium",
                    research_vocabs.fields.ConceptField(
                        default="rock",
                        editable=False,
                        verbose_name="medium",
                        vocabulary=earth_science.vocabularies.odm2.Medium,
                    ),
                ),
                (
                    "specimen_type",
                    research_vocabs.fields.ConceptField(
                        default="thinSection",
                        editable=False,
                        verbose_name="specimen",
                        vocabulary=earth_science.vocabularies.odm2.SpecimenType,
                    ),
                ),
            ],
            options={
                "verbose_name": "thin section",
                "verbose_name_plural": "thin sections",
                "abstract": False,
            },
            bases=("samples.sample",),
        ),
    ]
