# Generated by Django 3.2.16 on 2022-12-28 15:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.PositiveSmallIntegerField(help_text='plate ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='plate name', max_length=100)),
                ('reference', models.CharField(help_text='reference', max_length=100, null=True)),
                ('plate', models.CharField(help_text='plate', max_length=100)),
                ('subplate_id', models.IntegerField(help_text='Latitude in decimal degrees')),
                ('subplate_code', models.CharField(help_text='Latitude in decimal degrees', max_length=3)),
                ('subplate', models.CharField(help_text='Latitude in decimal degrees', max_length=128)),
                ('type', models.CharField(help_text='Latitude in decimal degrees', max_length=64)),
                ('crust_type', models.CharField(help_text='Latitude in decimal degrees', max_length=12)),
                ('sea_name', models.CharField(help_text='Latitude in decimal degrees', max_length=100, null=True)),
                ('domain', models.CharField(help_text='Latitude in decimal degrees', max_length=100, null=True)),
                ('area', models.FloatField(help_text='Latitude in decimal degrees')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
