# Generated by Django 3.2.16 on 2022-12-28 15:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=80)),
                ('reference', models.CharField(max_length=80, null=True)),
                ('group', models.CharField(max_length=80, null=True)),
                ('last_orogen', models.CharField(max_length=80, null=True)),
                ('continent', models.CharField(max_length=80, null=True)),
                ('conjugate_1', models.CharField(max_length=80, null=True)),
                ('comment', models.CharField(max_length=254, null=True)),
                ('crust_type', models.CharField(max_length=12)),
                ('conjugate_2', models.CharField(max_length=64, null=True)),
                ('area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
